dist: trusty
cache: ccache
language: c

env:
    matrix:
    - RUN_ON_CONTAINER=ubuntu-16.04
    #- RUN_ON_CONTAINER=ubuntu-12.04
    #- RUN_ON_CONTAINER=ubuntu-latest
    #- RUN_ON_CONTAINER=centos6
    #- RUN_ON_CONTAINER=centos7
    #- RUN_ON_CONTAINER=fedora24
    #- RUN_ON_CONTAINER=fedora25
    #- RUN_ON_CONTAINER=fedora-rawhide

matrix:
  allow_failures:
    - env: RUN_ON_CONTAINER=fedora-rawhide

sudo: required
services: docker

script:
        - docker build --pull -t ${RUN_ON_CONTAINER} -f ci/Dockerfile-${RUN_ON_CONTAINER} . &&
          docker run --volume $HOME/.ccache:/root/.ccache --rm -t $RUN_ON_CONTAINER;


